module.exports = {
  SET_HIDDEN_CARDS: 'SET_HIDDEN_CARDS',
  GET_HIDDEN_CARDS: 'GET_HIDDEN_CARDS',
  HIDE_CARD: 'HIDE_CARD',
  SHOW_CARD: 'SHOW_CARD',
  UPDATE_CARDS_LIST: 'UPDATE_CARDS_LIST',
  GET_CARDS_LIST: 'GET_CARDS_LIST'
}
