module.exports = {
  EMPLOYMENTS_FAIL: 'EMPLOYMENTS_FAIL',
  GET_ALL_EMPLOYMENTS: 'GET_ALL_EMPLOYMENTS',
  CREATE_EMPLOYMENT: 'CREATE_EMPLOYMENT',
  UPDATE_EMPLOYMENT: 'UPDATE_EMPLOYMENT',
  REMOVE_EMPLOYMENT: 'REMOVE_EMPLOYMENT'
}
