module.exports = {
  GET_ALL_LOCATIONS: 'GET_ALL_LOCATIONS',
  GET_MY_LOCATIONS: 'GET_MY_LOCATIONS',
  ADD_LOCATION: 'ADD_LOCATION',
  REMOVE_LOCATION: 'REMOVE_LOCATION',
  SAVE_LOCATIONS: 'SAVE_LOCATIONS',
  REVERT_CHANGES: 'REVERT_CHANGES'
}
