module.exports = {
  MOTIVATIONS_FAIL: 'MOTIVATIONS_FAIL',
  GET_ALL_MOTIVATIONS: 'GET_ALL_MOTIVATIONS',
  GET_MY_MOTIVATIONS: 'GET_MY_MOTIVATIONS',
  ADD_MOTIVATION: 'ADD_MOTIVATION',
  REMOVE_MOTIVATION: 'REMOVE_MOTIVATION',
  SAVE_MOTIVATIONS: 'SAVE_MOTIVATIONS'
}