module.exports = {
  OCCUPATIONS_FAIL: 'OCCUPATIONS_FAIL',
  GET_ALL_OCCUPATIONS: 'GET_ALL_OCCUPATIONS',
  GET_MY_OCCUPATIONS: 'GET_MY_OCCUPATIONS',
  ADD_OCCUPATION: 'ADD_OCCUPATION',
  REMOVE_OCCUPATION: 'REMOVE_OCCUPATION',
  ORDER_OCCUPATIONS: 'ORDER_OCCUPATIONS',
  SAVE_OCCUPATIONS: 'SAVE_OCCUPATIONS'
}
