module.exports = {
  PERSONALITIES_FAIL: 'PERSONALITIES_FAIL',
  GET_ALL_PERSONALITIES: 'GET_ALL_PERSONALITIES',
  GET_MY_PERSONALITIES: 'GET_MY_PERSONALITIES',
  ADD_PERSONALITY: 'ADD_PERSONALITY',
  REMOVE_PERSONALITY: 'REMOVE_PERSONALITY',
  SAVE_PERSONALITIES: 'SAVE_PERSONALITIES'
}