module.exports = {
  REFERENCES_FAIL: 'REFERENCES_FAIL',
  GET_ALL_REFERENCES: 'GET_ALL_REFERENCES',
  CREATE_REFERENCE: 'CREATE_REFERENCE',
  UPDATE_REFERENCE: 'UPDATE_REFERENCE',
  REMOVE_REFERENCE: 'REMOVE_REFERENCE'
}
