module.exports = {
  SKILLS_FAIL: 'SKILLS_FAIL',
  GET_ALL_SKILLS: 'GET_ALL_SKILLS',
  GET_MY_SKILLS: 'GET_MY_SKILLS',
  ADD_SKILL: 'ADD_SKILL',
  REMOVE_SKILL: 'REMOVE_SKILL',
  SAVE_SKILLS: 'SAVE_SKILLS'
}
