module.exports = {
  GET_ALL_STORIES: 'GET_ALL_STORIES',
  GET_STORY: 'GET_STORY',
  ADD_STORY: 'ADD_STORY',
  UPDATE_STORY: 'UPDATE_STORY',
  DELETE_STORY: 'DELETE_STORY',
  GET_EVENT_TYPES: 'GET_EVENT_TYPES',
  ADD_STORY_EVENT: 'ADD_STORY_EVENT',
  GET_STORY_EVENTS: 'GET_STORY_EVENTS',
}
